### PR TITLE
30 more traffic

### PR DESCRIPTION
**Pull request by wtoorop**
Add a paragraph to the Security section that mentions that revalidation induces more traffic.
The option to only revalidate the root and the TLDs is also mentioned here.

### CODE REVIEW

**Review by shuque — COMMENTED** [review]
This is a good discussion.  Some comments ..

Personally, I think NS revalidation at all layers probably doesn't cause enough additional queries to concern resolver implementers. Glue revalidation (where glue can be scattered across many zones) may cause a much more appreciable number of extra queries that may concern some resolver implementers. Maybe that difference could be highlighted somewhere?

**Review by vixie — COMMENTED** [review]
this is nonsequitur. anywhere that a delegation can be made to another party (such as example.co.uk as a delegation from co.uk, or 150.104.24.in-addr.arpa from 24.in-addr.arpa) there's a need for rapid recognition of deletion or redelegation. in ip6.arpa the depth will be even greater. i see no merit whatsoever in this PR.

**Comment by wtoorop** [comment]
There are actually two issues discussed in this PR. One is "more traffic", which I'm happy to drop. Another is the suggestion to validate only the upper layers because it has the highest impact w.r.t. increased security and privacy, and also because the child NS RRset is more likely to be of good quality there. I think that argument may resonate with the people that favor parent-only resolving strategies because of robustness (i.e. ralf, petr and fijiwara).

I will create a new PR with this argument dropping the increased traffic case.

**Comment by wtoorop** [comment]
Close this in favor of #34

**Pull request closed without merging**
